menu:
  Home:
  Archives: archives
  Projects: projects

widgets:
- search
- about_me
- recent_posts
- disqus_recent_comments

excerpt_link: Read More

about_me:
  email: roy@binux.me
  twitter: roybinux
  github: binux
  gplus: RoyBinux

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss: true

comment_provider: disqus
